version: '3.8'

services:
  flask:
    container_name: flask
    build:
      context: ./Api_WEB  # Chemin vers votre code Flask
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    environment:
      - FLASK_APP=FlaskApp/app.py
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]

networks:
  mynetwork:
    driver: bridge
