version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.15.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mynetwork

  scraping:
    container_name: scraping
    build:
      context: ./gaultmillau_scraper
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - mynetwork
    command: ["scrapy", "crawl", "gaultmillau"]
    restart: "no"  # S'arrête une fois le scraping terminé

  flask:
    container_name: flask
    build:
      context: ./Api_WEB  # Dossier contenant le code Flask (à adapter si nécessaire)
    depends_on:
      scraping:
        condition: service_completed_successfully  # Démarre une fois le scraping terminé
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - FLASK_APP=FlaskApp/app.py
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]

networks:
  mynetwork:
    driver: bridge
